name: Update Years of Experience

on:
  push:
    paths:
      - '**/README.md'
  schedule:
    - cron: '0 0 1 * *' # Run monthly on the 1st

jobs:
  update-years:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update years of experience
        run: |
          START_YEAR=2021
          CURRENT_YEAR=$(date +%Y)
          CURRENT_MONTH=$(date +%m)
          YEARS=$((CURRENT_YEAR - START_YEAR))
          if [ "$CURRENT_MONTH" -lt 1 ]; then
            YEARS=$((YEARS - 1))
          fi
          sed -i.bak "s/{{CURRENT_YEARS}}/${YEARS}/g" README.md
          rm README.md.bak

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "chore: auto-update years of experience" || echo "No changes to commit"
          git push