name: Update Experience Years in README

on:
  schedule:
    - cron: '0 0 1 1 *' # Runs yearly on January 1st at midnight UTC
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-experience:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Ensure docs directory exists
        run: mkdir -p docs
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run update-experience script
        run: node update-experience.js
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update years of experience in README [auto]'
          file_pattern: README.md
